Fix compilation error in CpuArc (#163)
Summary:
Pull Request resolved: https://github.com/facebookincubator/dynolog/pull/163

Noticed some build failures when `-Werror,-Wunused-parameter` is used:
```
 buck-out/v2/gen/fbcode/d9c9d105b3705280/hbt/src/perf_event/__CpuArch__/buck-headers/hbt/src/perf_event/CpuArch.h:30:41: error: unused parameter 'cpu_family' [-Werror,-Wunused-parameter]
```

Reviewed By: nslingerland

Differential Revision: D47472700

fbshipit-source-id: 689e7e5cc8c7e9382e1d2a52c4b554756256f4ad