Fix compilation error in CpuArc (#163)
Summary:
Pull Request resolved: https://github.com/facebookincubator/dynolog/pull/163

Noticed some build failures when `-Werror,-Wunused-parameter` is used:
```
 buck-out/v2/gen/fbcode/d9c9d105b3705280/hbt/src/perf_event/__CpuArch__/buck-headers/hbt/src/perf_event/CpuArch.h:30:41: error: unused parameter 'cpu_family' [-Werror,-Wunused-parameter]
```

Reviewed By: nslingerland, briancoutinho

Differential Revision: D47472700

fbshipit-source-id: 21a305e58bd3654bcb2bb0dba60f783b9fc23830